export const bikes = [
    {
        id: 1,
        name: "Honda SP 125",
        image: "https://cdn.bikedekho.com/processedimages/honda/sp125/source/sp1256789ead2971d1.jpg?tr=w-300",
        priceRange: "₹92,678 - 1 Lakh",
        priceNote: "View On Road Price",
        rating: 4.5,
        reviews: 134,
        mileage: "63 kmpl",
        engine: "123.94 cc",
        power: "10.87 PS",
        offerText: "View June Offers",
    },
    {
        id: 2,
        name: "TVS Raider 125",
        image: "https://cdn.bikedekho.com/processedimages/honda/sp125/source/sp1256789ead2971d1.jpg?tr=w-300",
        priceRange: "₹95,219 - ₹1.02 Lakh",
        priceNote: "View On Road Price",
        rating: 4.6,
        reviews: 210,
        mileage: "67 kmpl",
        engine: "124.8 cc",
        power: "11.4 PS",
        offerText: "Get Summer Deals",
    },
    {
        id: 3,
        name: "Hero Splendor Plus",
        image: "https://cdn.bikedekho.com/processedimages/honda/sp125/source/sp1256789ead2971d1.jpg?tr=w-300",
        priceRange: "₹75,141 - ₹76,486",
        priceNote: "View On Road Price",
        rating: 4.3,
        reviews: 289,
        mileage: "80.6 kmpl",
        engine: "97.2 cc",
        power: "8.02 PS",
        offerText: "Check July Offers",
    },
    {
        id: 4,
        name: "Bajaj Pulsar 150",
        image: "https://cdn.bikedekho.com/processedimages/honda/sp125/source/sp1256789ead2971d1.jpg?tr=w-300",
        priceRange: "₹1.13 - ₹1.17 Lakh",
        priceNote: "View On Road Price",
        rating: 4.4,
        reviews: 415,
        mileage: "47 kmpl",
        engine: "149.5 cc",
        power: "14 PS",
        offerText: "View Festive Offers",
    },
    {
        id: 5,
        name: "Yamaha FZ-S FI V4",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/137217/fz-s-fi-v4-right-side-view.png",
        priceRange: "₹1.28 Lakh",
        priceNote: "View On Road Price",
        rating: 4.2,
        reviews: 192,
        mileage: "45 kmpl",
        engine: "149 cc",
        power: "12.4 PS",
        offerText: "Explore Cashback",
    },
    {
        id: 6,
        name: "KTM 200 Duke",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/137635/200-duke-right-side-view.png",
        priceRange: "₹1.96 Lakh",
        priceNote: "View On Road Price",
        rating: 4.7,
        reviews: 98,
        mileage: "35 kmpl",
        engine: "199.5 cc",
        power: "25 PS",
        offerText: "Check Performance Deals",
    },
];
export const scooters = [
    {
        id: 1,
        name: "Honda Activa 6G",
        image: "https://cdn.bikedekho.com/processedimages/honda/activa-6g/source/activa-6g65e80a97062a4.jpg?tr=w-89",
        priceRange: "₹77,712 - ₹83,712",
        priceNote: "View On Road Price",
        rating: 4.4,
        reviews: 312,
        mileage: "50 kmpl",
        engine: "109.51 cc",
        power: "7.84 PS",
        offerText: "Check June Offers",
    },
    {
        id: 2,
        name: "TVS Jupiter",
        image: "https://cdn.bikedekho.com/processedimages/honda/activa-6g/source/activa-6g65e80a97062a4.jpg?tr=w-89",
        priceRange: "₹75,000 - ₹85,673",
        priceNote: "View On Road Price",
        rating: 4.3,
        reviews: 275,
        mileage: "50 kmpl",
        engine: "109.7 cc",
        power: "7.88 PS",
        offerText: "Summer Offers Available",
    },
    {
        id: 3,
        name: "Suzuki Access 125",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/141059/access-125-right-side-view.png",
        priceRange: "₹79,899 - ₹89,500",
        priceNote: "View On Road Price",
        rating: 4.5,
        reviews: 215,
        mileage: "52.5 kmpl",
        engine: "124 cc",
        power: "8.7 PS",
        offerText: "Limited Period Offer",
    },
    {
        id: 4,
        name: "Hero Pleasure Plus",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/139683/pleasure-plus-right-side-view.png",
        priceRange: "₹72,000 - ₹78,000",
        priceNote: "View On Road Price",
        rating: 4.2,
        reviews: 198,
        mileage: "50 kmpl",
        engine: "110.9 cc",
        power: "8.1 PS",
        offerText: "Explore Cashback",
    },
    {
        id: 5,
        name: "OLA S1 Air",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/137647/s1-air-right-side-view.png",
        priceRange: "₹1.10 Lakh",
        priceNote: "View On Road Price",
        rating: 4.6,
        reviews: 142,
        mileage: "121 km/charge",
        engine: "Electric",
        power: "4.5 kW",
        offerText: "Electric Scooter Deals",
    },
    {
        id: 6,
        name: "Ather 450X",
        image: "https://imgd.aeplcdn.com/1056x594/n/cw/ec/140847/450x-right-side-view.png",
        priceRange: "₹1.42 Lakh - ₹1.59 Lakh",
        priceNote: "View On Road Price",
        rating: 4.7,
        reviews: 120,
        mileage: "146 km/charge",
        engine: "Electric",
        power: "6.4 kW",
        offerText: "Check Performance Offers",
    },
];
  
  