import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { GoogleOAuthProvider } from '@react-oauth/google';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <GoogleOAuthProvider clientId="771090578601-do73vpbpujjpkrugqlsb5eap83sksjtg.apps.googleusercontent.com"> */}
          {children}
        {/* </GoogleOAuthProvider> */}
      </body>
    </html>
  );
}

