export const carsData = [
    {
        id: 1,
        name: "Kia Soul 2016",
        brand: "KIA",
        price: 80,
        location: "Belgium",
        fuel: "Petrol",
        fuelAlt: "Diesel",
        type: "Auto",
        distance: "22 KM",
        year: 2016,
        persons: 5,
        rating: 4.0,
        reviews: 170,
        timeAgo: "4.0m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        images:
            [
            "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
            "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-02.jpg",
            "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-03.jpg",
            "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-04.jpg"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 4,
    },
    {
        id: 2,
        name: "Toyota Camry SE",
        brand: "Toyota",
        price: 120,
        location: "USA",
        fuel: "Diesel",
        fuelAlt: "Electric",
        type: "Sedan",
        distance: "35 KM",
        year: 2020,
        persons: 5,
        rating: 4.5,
        reviews: 198,
        timeAgo: "3.5m",
        images:
            [
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-02.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-03.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-04.jpg"
            ],
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 6,
    },
    {
        id: 3,
        name: "Audi A4",
        brand: "Audi",
        price: 150,
        location: "Germany",
        fuel: "Petrol",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "28 KM",
        year: 2019,
        persons: 4,
        rating: 4.8,
        reviews: 221,
        timeAgo: "2.2m",
        images:
            [
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-02.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-03.jpg",
                "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-04.jpg"
            ],
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 8,
    },
    {
        id: 4,
        name: "Honda Civic",
        brand: "Honda",
        price: 90,
        location: "Japan",
        fuel: "Diesel",
        fuelAlt: "Petrol",
        type: "Hatchback",
        distance: "19 KM",
        year: 2018,
        persons: 5,
        rating: 4.2,
        reviews: 140,
        timeAgo: "5.1m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 5,
    },
    {
        id: 5,
        name: "Ford Mustang",
        brand: "Ford",
        price: 200,
        location: "USA",
        fuel: "Petrol",
        fuelAlt: "Hybrid",
        type: "Coupe",
        distance: "45 KM",
        year: 2021,
        persons: 2,
        rating: 4.9,
        reviews: 342,
        timeAgo: "1.0m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 10,
    },
    {
        id: 6,
        name: "Hyundai i20",
        brand: "Hyundai",
        price: 70,
        location: "India",
        fuel: "Petrol",
        fuelAlt: "CNG",
        type: "Hatchback",
        distance: "12 KM",
        year: 2017,
        persons: 5,
        rating: 3.9,
        reviews: 98,
        timeAgo: "6.2m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 3,
    },
    {
        id: 7,
        name: "BMW 5 Series",
        brand: "BMW",
        price: 180,
        location: "Germany",
        fuel: "Diesel",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "40 KM",
        year: 2022,
        persons: 4,
        rating: 4.6,
        reviews: 251,
        timeAgo: "2.8m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 7,
    },
    {
        id: 8,
        name: "Tesla Model 3",
        brand: "Tesla",
        price: 220,
        location: "USA",
        fuel: "Electric",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "15 KM",
        year: 2023,
        persons: 5,
        rating: 4.9,
        reviews: 410,
        timeAgo: "0.8m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 12,
    },
    {
        id: 9,
        name: "Volkswagen Polo",
        brand: "Volkswagen",
        price: 65,
        location: "Poland",
        fuel: "Petrol",
        fuelAlt: "CNG",
        type: "Hatchback",
        distance: "10 KM",
        year: 2015,
        persons: 5,
        rating: 3.8,
        reviews: 85,
        timeAgo: "6.5m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 4,
    },
    {
        id: 10,
        name: "Nissan Altima",
        brand: "Nissan",
        price: 100,
        location: "UAE",
        fuel: "Petrol",
        fuelAlt: "Diesel",
        type: "Sedan",
        distance: "30 KM",
        year: 2018,
        persons: 5,
        rating: 4.1,
        reviews: 132,
        timeAgo: "4.2m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 5,
    },

    {
        id: 11,
        name: "Kia Soul 2016",
        brand: "KIA",
        price: 80,
        location: "Belgium",
        fuel: "Petrol",
        fuelAlt: "Diesel",
        type: "Auto",
        distance: "22 KM",
        year: 2016,
        persons: 5,
        rating: 4.0,
        reviews: 170,
        timeAgo: "4.0m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 4,
    },
    {
        id: 12,
        name: "Toyota Camry SE",
        brand: "Toyota",
        price: 120,
        location: "USA",
        fuel: "Diesel",
        fuelAlt: "Electric",
        type: "Sedan",
        distance: "35 KM",
        year: 2020,
        persons: 5,
        rating: 4.5,
        reviews: 198,
        timeAgo: "3.5m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 6,
    },
    {
        id: 13,
        name: "Audi A4",
        brand: "Audi",
        price: 150,
        location: "Germany",
        fuel: "Petrol",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "28 KM",
        year: 2019,
        persons: 4,
        rating: 4.8,
        reviews: 221,
        timeAgo: "2.2m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 8,
    },
    {
        id: 14,
        name: "Honda Civic",
        brand: "Honda",
        price: 90,
        location: "Japan",
        fuel: "Diesel",
        fuelAlt: "Petrol",
        type: "Hatchback",
        distance: "19 KM",
        year: 2018,
        persons: 5,
        rating: 4.2,
        reviews: 140,
        timeAgo: "5.1m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 5,
    },
    {
        id: 15,
        name: "Ford Mustang",
        brand: "Ford",
        price: 200,
        location: "USA",
        fuel: "Petrol",
        fuelAlt: "Hybrid",
        type: "Coupe",
        distance: "45 KM",
        year: 2021,
        persons: 2,
        rating: 4.9,
        reviews: 342,
        timeAgo: "1.0m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 10,
    },
    {
        id: 16,
        name: "Hyundai i20",
        brand: "Hyundai",
        price: 70,
        location: "India",
        fuel: "Petrol",
        fuelAlt: "CNG",
        type: "Hatchback",
        distance: "12 KM",
        year: 2017,
        persons: 5,
        rating: 3.9,
        reviews: 98,
        timeAgo: "6.2m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 3,
    },
    {
        id: 17,
        name: "BMW 5 Series",
        brand: "BMW",
        price: 180,
        location: "Germany",
        fuel: "Diesel",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "40 KM",
        year: 2022,
        persons: 4,
        rating: 4.6,
        reviews: 251,
        timeAgo: "2.8m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 7,
    },
    {
        id: 18,
        name: "Tesla Model 3",
        brand: "Tesla",
        price: 220,
        location: "USA",
        fuel: "Electric",
        fuelAlt: "Hybrid",
        type: "Sedan",
        distance: "15 KM",
        year: 2023,
        persons: 5,
        rating: 4.9,
        reviews: 410,
        timeAgo: "0.8m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 12,
    },
    {
        id: 19,
        name: "Volkswagen Polo",
        brand: "Volkswagen",
        price: 65,
        location: "Poland",
        fuel: "Petrol",
        fuelAlt: "CNG",
        type: "Hatchback",
        distance: "10 KM",
        year: 2015,
        persons: 5,
        rating: 3.8,
        reviews: 85,
        timeAgo: "6.5m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 4,
    },
    {
        id: 20,
        name: "Nissan Altima",
        brand: "Nissan",
        price: 100,
        location: "UAE",
        fuel: "Petrol",
        fuelAlt: "Diesel",
        type: "Sedan",
        distance: "30 KM",
        year: 2018,
        persons: 5,
        rating: 4.1,
        reviews: 132,
        timeAgo: "4.2m",
        image: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/cars/car-01.jpg",
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 5,
    }
];
