export const carsData = [
    {
        id: 1,
        name: "Ather 450X",
        brand: "Ather",
        price: 105,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "60 KM",
        year: 2023,
        persons: 2,
        rating: 4.5,
        reviews: 210,
        timeAgo: "3.2m",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdAGSOVt11fY8nUlMw9ohgTf35uQ5jdDM4Lw&s",
        images: [
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdAGSOVt11fY8nUlMw9ohgTf35uQ5jdDM4Lw&s"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    },
    {
        id: 2,
        name: "Ola S1 Pro",
        brand: "Ola Electric",
        price: 110,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "75 KM",
        year: 2024,
        persons: 2,
        rating: 4.6,
        reviews: 325,
        timeAgo: "2.7m",
        image: "https://assets.otocapital.in/production/amethyst-ola-s1-pro-image.png",
        images: [
            "https://assets.otocapital.in/production/amethyst-ola-s1-pro-image.png"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    },
    {
        id: 3,
        name: "TVS iQube",
        brand: "TVS",
        price: 95,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "50 KM",
        year: 2023,
        persons: 2,
        rating: 4.2,
        reviews: 180,
        timeAgo: "4.4m",
        image: "https://img-cdn.evfy.in/products/iqube-PrimaryImage.webp",
        images: [
            "https://img-cdn.evfy.in/products/iqube-PrimaryImage.webp"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    },
    {
        id: 4,
        name: "Vida V1 Pro",
        brand: "Hero Electric",
        price: 100,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "60 KM",
        year: 2023,
        persons: 2,
        rating: 4.3,
        reviews: 195,
        timeAgo: "3.9m",
        image: "https://rukminim3.flixcart.com/image/850/1000/xif0q/electric-bike-scooter/c/q/x/-original-imagz8xnkeykwmpc.jpeg?q=90&crop=false",
        images: [
            "https://rukminim3.flixcart.com/image/850/1000/xif0q/electric-bike-scooter/c/q/x/-original-imagz8xnkeykwmpc.jpeg?q=90&crop=false"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    },
    {
        id: 5,
        name: "Bajaj Chetak EV",
        brand: "Bajaj",
        price: 98,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "55 KM",
        year: 2022,
        persons: 2,
        rating: 4.1,
        reviews: 160,
        timeAgo: "5.2m",
        image: "https://cdn.bajajauto.com/-/media/chetakv2/content-image/image-series/3502_image.webp",
        images: [
            "https://cdn.bajajauto.com/-/media/chetakv2/content-image/image-series/3502_image.webp"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    },
    {
        id: 6,
        name: "Ola S1 Air",
        brand: "Ola Electric",
        price: 88,
        location: "India",
        fuel: "Electric",
        fuelAlt: "N/A",
        type: "Scooter",
        distance: "50 KM",
        year: 2024,
        persons: 2,
        rating: 4.4,
        reviews: 200,
        timeAgo: "2.3m",
        image: "https://imgd.aeplcdn.com/1280x720/n/bw/models/colors/ola-select-model-neon-1690531574765.jpg",
        images: [
            "https://imgd.aeplcdn.com/1280x720/n/bw/models/colors/ola-select-model-neon-1690531574765.jpg"
        ],
        userImg: "https://dreamsrent.dreamstechnologies.com/html/template/assets/img/profiles/avatar-04.jpg",
        photoCount: 1,
    }
];
